[logger]
level = "INFO"

[storage]
type = "sql"
dsn = "postgres://calendar:calendar@postgres:5432/calendar?sslmode=disable"

[HTTPServer]
host = "0.0.0.0"
port = "8888"

[GRPCServer]
host = "0.0.0.0"
port = "50051"