[logger]
level = "INFO"

[storage]
type = "sql"
dsn = "postgres://calendar:calendar@postgres:5432/calendar?sslmode=disable"

[queue]
type = "rmq"
dsn = "amqp://guest:guest@rabbit:5672"
queue = "notifications"

[intervals]
notify = "60s"
delete = "1m"