[logger]
level = "INFO"

[storage]
type = "sql"
dsn = "postgres://calendar:calendar@postgres:5432/calendar?sslmode=disable"

[queue]
type = "rmq"
dsn = "amqp://guest:guest@rabbit:5672"
exchange = "notifications"
exchangeType = "fanout"
queue = "notifications"
